# Generated by Django 3.1.1 on 2020-09-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=160)),
                ('model', models.CharField(max_length=160)),
                ('serial_number', models.CharField(max_length=20)),
            ],
        ),
    ]
