# Generated by Django 3.1.1 on 2020-11-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Extra', 'Extra'), ('Light', 'Light'), ('Power', 'Power'), ('Sound', 'Sound'), ('Stage', 'Stage')], default='Extra', max_length=10),
        ),
    ]
